export enum ActionHandlerCategory {
  Atlassian = "Atlassian",
  Aws = "Aws",
  Azure = "Azure",
  BuiltInStep = "BuiltInStep",
  Certificate = "Certificate",
  Community = "Community",
  CommunitySubCategory = "CommunitySubCategory",
  Docker = "Docker",
  GoogleCloud = "Google",
  JavaAppServer = "JavaAppServer",
  Kubernetes = "Kubernetes",
  Other = "Other",
  Package = "Package",
  Script = "Script",
  StepTemplate = "StepTemplate",
  Terraform = "Terraform",
  WindowsServer = "WindowsServer",
}
