import type { ResourceWithLinks } from "./resource";

export type SpaceRootLinks = {
  Accounts: string;
  ActionTemplates: string;
  ActionTemplatesCategories: string;
  ActionTemplatesSearch: string;
  ActionTemplateLogo: string;
  ActionTemplateVersionedLogo: string;
  Artifacts: string;
  Channels: string;
  Certificates: string;
  Dashboard: string;
  DashboardConfiguration: string;
  DashboardDynamic: string;
  DeploymentProcesses: string;
  Deployments: string;
  DiscoverMachine: string;
  DiscoverWorker: string;
  Environments: string;
  EnvironmentsSummary: string;
  EnvironmentSortOrder: string;
  ExportProjects: string;
  Feeds: string;
  BuiltInFeedStats: string;
  ImportProjects: string;
  ProjectImportFiles: string;
  ProjectImportPreview: string;
  Interruptions: string;
  LibraryVariables: string;
  Lifecycles: string;
  MachinePolicies: string;
  MachinePolicyTemplate: string;
  MachineRoles: string;
  MachineShells: string;
  MachineOperatingSystems: string;
  Machines: string;
  Runbooks: string;
  RunbookProcesses: string;
  RunbookSnapshots: string;
  RunbookRuns: string;
  PackageMetadata: string;
  BuildInformation: string;
  BuildInformationBulk: string;
  Packages: string;
  PackagesBulk: string;
  PackageUpload: string;
  PackageDeltaSignature: string;
  PackageDeltaUpload: string;
  PackageNotesList: string;
  ProjectGroups: string;
  Projects: string;
  ProjectsExperimentalSummaries: string;
  ProjectTriggers: string;
  ProjectPulse: string;
  Proxies: string;
  Releases: string;
  "Reporting/DeploymentsCountedByWeek": string;
  Subscriptions: string;
  TagSets: string;
  TagSetSortOrder: string;
  Tenants: string;
  TenantsStatus: string;
  TenantVariables: string;
  TenantTagTest: string;
  TenantsMissingVariables: string;
  UserOnboarding: string;
  Variables: string;
  VariableNames: string;
  VariablePreview: string;
  VersionRuleTest: string;
  WorkerPools: string;
  WorkerPoolsSummary: string;
  Workers: string;
  WorkerShells: string;
  WorkerOperatingSystems: string;
  WorkerPoolsSortOrder: string;
  WorkerPoolsSupportedTypes: string;
  WorkerPoolsDynamicWorkerTypes: string;
  SpaceSearch: string;
};

export type SpaceRootResource = ResourceWithLinks<
  SpaceRootLinks & { Self: string }
>;
